rex2/models.py
import sqlite3
conn = sqlite3.connect('rex.db')
c = conn.cursor()
c.execute("CREATE TABLE messages (id text, user text, message text)")
conn.commit()

rex2/__init__.py
from flask import Flask
from .routes import mainbp, people, messages, fns
from flask_sse import sse
import sqlite3, logging
from flask_executor import Executor
app = Flask(__name__, template_folder="templates")
executor = Executor(app)
app.config["REDIS_URL"] = "redis://localhost:6379"
app.config["SECRET_KEY"] = "abcdefg"
app.register_blueprint(sse, url_prefix='/stream')
app.register_blueprint(mainbp)
app.register_blueprint(people, url_prefix='/people')
app.register_blueprint(messages, url_prefix='/message')
app.context_processor(fns)
conn = sqlite3.connect('rex.db')
def main():
    for route in app.url_map.iter_rules():
        logging.info(route)
    app.run()

rex2/routes/__init__.py
from .people import people #type:ignore 
from .messages import messages, fns #type:ignore
from flask import Blueprint, render_template, session
from ..scans import task, a

mainbp = Blueprint('main', __name__)  
@mainbp.route('/')
def index():
    from .. import executor
    if len(executor.futures) == 0:
        session["name"] = "pbk"
        executor.submit(task)
        executor.submit(a)
    return render_template('index.html')

rex2/routes/messages.py
from flask import Blueprint, request,session
import json
import sqlite3
import logging
import mqttudp.engine as me

messages = Blueprint('messages', __name__)

@messages.route('/', methods=['POST'])
def message():
    print(request.form)
    data = request.form
    logging.info("relaying message: %s", data["message"])
    conn = sqlite3.connect('rex.db')
    c = conn.cursor()
    last_id = c.execute("SELECT * FROM messages WHERE user=? ORDER BY id DESC LIMIT 1", (session["name"],)).fetchone()
    if last_id is None or len(last_id) == 0:
        last_id =[ 0]
    c.execute("INSERT INTO messages VALUES (?,?,?)",(int(last_id[0])+1,session["name"],data["message"]))
    conn.commit()
    conn.close()
    me.send_publish("message", json.dumps({"id":int(last_id[0])+1,"name":session["name"],"message":data["message"]}).encode())
    return "OK"

def fns():
    def previous():
        conn = sqlite3.connect('rex.db')
        c = conn.cursor()
        c.execute("SELECT * FROM messages")
        l = c.fetchall()
        conn.close()
        return json.dumps(l)
    return dict(previous=previous)

rex2/routes/people.py
from flask import Blueprint, request
from flask_sse import sse

people = Blueprint('people', __name__)

@people.route('/publish_internal', methods=['POST'])
def publish_internal():
    name = request.form.get("name")
    strength = request.form.get("strength")
    address = request.form.get("address")
    sse.publish({"name":name,"ip":address+"     "+strength}, type='ping')
    return "OK"

rex2/templates/index.html
<head>
  <style>
    .dialog {
      width: 100vw;
      height: 100vh;
      position: fixed;
      top: 0;
      left: 0;
      z-index: 100;
      background-color: rgba(0, 0, 0, 0.2);
      backdrop-filter: blur(5px);
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
    }
    .dialog > div {
      background-color: #ffffff;
      border-radius: 10px;
      padding: 10px;
      width: 20vw;
      height: 20vh;
    }
    .dialog > div > form {
      display: flex;
      width: calc(100% - 10px);
      height: calc(100% - 30px);
      flex-direction: column;
      justify-content: center;
      align-items: center;
      margin-top: 20px;
      padding-left: 5px;
      padding-right: 5px;
      margin-bottom: 0px;
      padding-bottom: 0px;
    }
    .open-dialog {
      position: fixed;
      bottom: 20px;
      right: 20px;
      width: 50px;
      height: 50px;
      border-radius: 50%;
      background-color: #00ff00;
      color: #ffffff;
      font-size: 30px;
      border: none;
      outline: none;
      z-index: 50;
    }
    .close-dialog {
      position: relative;
      top: 0;
      right: 0;
      width: 30px;
      height: 30px;
      border-radius: 50%;
      font-size: 20px;
      border: none;
      outline: none;
    }
    .send {
      display: flex;
      flex-direction: row;
      justify-content: center;
      align-items: center;
      height: calc(100% - 20px);
      border: 1px solid #000000;
      border-radius: 10px;
    }
    .send-text {
      width: calc(100% - 50px);
      height: 100%;
      border: none;
      outline: none;
      resize: none;
      font-size: 20px;
      border-top-left-radius: 10px;
      border-bottom-left-radius: 10px;
    }
    .send-btns-area {
      display: flex;
      flex-direction: column;
      justify-content: space-evenly;
      align-items: center;
      width: 50px;
      height: 100%;
    }
    .send-btn {
      width: 45px;
      height: 45px;
      border: none;
      outline: none;
      color:#888;
      font-size: 30px;
      display: flex;
      background-color: transparent;
      justify-content: center;
      align-items: center;
    }
    /*make the scroll bar for .send-text look better for all browsers*/
    .send-text::-webkit-scrollbar {
      width: 2px;
    }
    .send-text::-webkit-scrollbar-track {
      background: #f1f1f1;
    }
    .send-text::-webkit-scrollbar-thumb {
      background: #888;
    }
    .message-container {
      display: flex;
      justify-content: right;
      align-items: center;
      align-content: center;
      width: 100vw;
      flex-direction: column-reverse;
      margin: 0;
      padding: 0;
    }
    .cards-container {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        align-items: center;
        align-content: center;
        flex-direction: row;
    }
    .card {
        margin: 10px;
        width: 300px;
        min-height: 100px;
        border: 1px solid #ccc;
        border-radius: 35px;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        align-items: center;
        align-content: center;
        padding: 10px;
    }
    .card img {
        width: 100%;
        height: 100%;
        object-fit: cover;
    }
    .card:hover{
        transform: scale(1.1);
    }
    .card-pfp-text {
        position: absolute;
        flex-shrink: 0;
        font-size: 1.5em;
        font-weight: bold;
        text-align: center;
        border-radius: 50%;
        display: flex;
        aspect-ratio: 1/1;
        text-align: center;
        justify-content: space-around;
        align-items: center;
        align-self: flex-start;
        align-content: center;
        width: 50px;
        background-color: black;
        color: white;
        z-index: 200;
    }
    .card-title {
        font-size: 1.5em;
        flex-wrap: nowrap;
        align-items: center;
        justify-content: center;
        width: 100%;
    }
    .card-header{
        flex-shrink: 0;
        width: 100%;
        font-weight: bold;
        align-items: center;
        margin-left: auto;
        margin-right: auto;
        text-align: center;
        z-index: 100;
    }
    
    .card-content {
        font-size: 1.2em;
        width: 100%;
        text-align: center;
    }
    .card-footer {
        text-align: end;
        width: 100%;
        color: #ccc;
        box-shadow: 1px 2px 3px 4px solid black;
    }
    /*create some background color classes*/
    .bg-red {
        background-color: red;
    }
    .bg-green {
        background-color: green;
    }
    .bg-blue {
        background-color: blue;
    }
    .bg-yellow {
        background-color: yellow;
    }
    .bg-orange {
        background-color: orange;
    }
    .bg-purple {
        background-color: purple;
    }
    .bg-pink {
        background-color: pink;
    }
    .bg-black {
        background-color: black;
    }
    .message {
      margin: 10px;
      width: 100%;
      box-shadow: 0px 1px 0px 0px #ccc;
      display: flex;
      flex-direction: column;
      justify-content: start;
      align-items: center;
      align-content: center;
      padding: 10px;
  }
  </style>
  <script>
    let timeouts = new Map();
    let people_colors = new Map();
    const COLORS = ["red", "green", "blue", "yellow", "orange", "purple", "pink", "black"];
    const TIMEOUT = 5000;
    window.onload = () => {
      document.getElementById("send1").addEventListener("submit", (e) => {
        e.preventDefault();
        let form = document.getElementById("send1");
        let formData = new FormData(form);
        for(let pair of formData.entries()) {
          console.log(pair[0]+ ', '+ pair[1]);
        }
        fetch("{{ url_for('messages.message') }}", {
          method: "POST",
          body: formData,
        }).then(async (res) => {
          await res;
          document.getElementById("nm").style.display = "none";
        });
      });
      document.getElementById("od1").addEventListener("click", () => {
        document.getElementById("nm").style.display = "flex";
      });
      document.getElementById("cd1").addEventListener("click", () => {
        document.getElementById("nm").style.display = "none";
      });
      var source = new EventSource("{{ url_for('sse.stream') }}");
      source.addEventListener(
        "ping",
        function (event) {
          var data = JSON.parse(event.data);
          console.log("The server says " + event.data);
          if (timeouts.has(data.name)) {
            clearTimeout(timeouts.get(data.name));
            document.getElementById("dev-" + data.ip).querySelector(".card-footer").innerText = (new Date()).toLocaleString();
            timeouts.set(
              data.name,
              setTimeout(() => {
                document
                  .getElementById("active")
                  .removeChild(document.getElementById("dev-" + data.ip));
                timeouts.delete(data.name);
              }, TIMEOUT)
            );
          } else {
            let elem = document.createElement("div");
            elem.classList.add("card");
            elem.id = "dev-" + data.ip;
            let header = document.createElement("div");
            header.classList.add("card-header");
            header.innerText = data.name;
            let content = document.createElement("div");
            content.classList.add("card-content");
            content.innerText = data.ip;
            let pfp = document.createElement("div");
            pfp.classList.add("card-pfp-text");
            pfp.innerText = data.name[0];
            let color_class = people_colors.get(data.name);
            if (color_class == undefined) {
              color_class = COLORS[Math.floor(Math.random() * COLORS.length)];
              people_colors.set(data.name, color_class);
            }
            pfp.classList.add("bg-" + color_class);
            let footer = document.createElement("div");
            footer.classList.add("card-footer");
            footer.innerText = (new Date()).toLocaleString();
            header.appendChild(pfp);
            elem.appendChild(header);
            elem.appendChild(content);
            elem.appendChild(footer);
            document.getElementById("active").appendChild(elem);
            timeouts.set(
              data.name,
              setTimeout(() => {
                document.getElementById("active").removeChild(elem);
                timeouts.delete(data.name);
              }, TIMEOUT)
            );
          }
        },
        false
      );
      source.addEventListener(
        "message",
        function (event) {
          var data = JSON.parse(event.data);
          console.log("The server says " + event.data);
          let elem = document.createElement("div");
            elem.classList.add("message");
            elem.id = "msg-" + data.id;
            let header = document.createElement("div");
            header.classList.add("card-header");
            header.innerText = data.name;
            let content = document.createElement("div");
            content.classList.add("card-content");
            content.innerText = data.message;
            let pfp = document.createElement("div");
            pfp.classList.add("card-pfp-text");
            pfp.innerText = data.name[0];
            let color_class = people_colors.get(data.name);
            if (color_class == undefined) {
              color_class = COLORS[Math.floor(Math.random() * COLORS.length)];
              people_colors.set(data.name, color_class);
            }
            pfp.classList.add("bg-" + color_class);
            let footer = document.createElement("div");
            footer.classList.add("card-footer");
            footer.innerText = (new Date()).toLocaleString();
            header.appendChild(pfp);
            elem.appendChild(header);
            elem.appendChild(content);
            elem.appendChild(footer);
            document.getElementById("messages").appendChild(elem);
        },
        false
      );
      source.addEventListener(
        "error",
        function (event) {
          alert("Failed to connect to event stream. Is Redis running?");
        },
        false
      );
      let prev = {{ previous() | safe }};
      for(let row of prev){
        let [id, name, message] = row;
        let elem = document.createElement("div");
            elem.classList.add("message");
            elem.id = "msg-" + id;
            let header = document.createElement("div");
            header.classList.add("card-header");
            header.innerText = name;
            let content = document.createElement("div");
            content.classList.add("card-content");
            content.innerText = message;
            let pfp = document.createElement("div");
            pfp.classList.add("card-pfp-text");
            pfp.innerText = name[0];
            let color_class = people_colors.get(name);
            if (color_class == undefined) {
              color_class = COLORS[Math.floor(Math.random() * COLORS.length)];
              people_colors.set(name, color_class);
            }
            pfp.classList.add("bg-" + color_class);
            let footer = document.createElement("div");
            footer.classList.add("card-footer");
            footer.innerText = "history";
            header.appendChild(pfp);
            elem.appendChild(header);
            elem.appendChild(content);
            elem.appendChild(footer);
            document.getElementById("messages").appendChild(elem);
      }
    };
  </script>
</head>
<h1>active</h1>
<div id="active" class="card-container"></div>
<h1>messages</h1>
<div id="messages" class="message-container">
</div>
<div id="nm" class="dialog" style="display: none">
  <div>
    <button class="close-dialog" id="cd1" type="reset">x</button>
    <form action="{{ url_for('messages.message') }}" method="post" id="send1">
      <div class="send">
        <textarea name="message" id="message" class="send-text"></textarea>
        <div class="send-btns-area">
          <button class="send-btn">></button>
          <input type="file" name="file" id="file" accept=".jpg,.png" hidden />
          <label for="file" class="send-btn">+</label>
        </div>
      </div>
    </form>
  </div>
</div>
<button class="open-dialog" id="od1" type="button">+</button>